/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_power_pairhmm_PowerPairHMM */

#ifndef _Included_com_ibm_power_pairhmm_PowerPairHMM
#define _Included_com_ibm_power_pairhmm_PowerPairHMM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_power_pairhmm_PowerPairHMM
 * Method:    subComputeReadLikelihoodGivenHaplotypeLog10Native
 * Signature: (III[[D[[D[[D[[D[[D)D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_power_pairhmm_PowerPairHMM_subComputeReadLikelihoodGivenHaplotypeLog10Native
  (JNIEnv *, jobject, jint, jint, jint, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
